# Generated by Django 3.2.18 on 2023-03-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230322_1656'),
        ('core', '0004_recipe_image'),
    ]

    operations = [
    ]
